### PR TITLE
Improve connection handling

### PR DESCRIPTION
**Pull request by kxconor**

### CODE REVIEW

**Comment by rymurr** [comment]
thanks @kxconor! I surmise the reason for this change was to make the kdb connection lazy?

**Comment by kxconor** [comment]
@rymurr Yes after some usage on dremio, it was not possible to communicate with the KDB data source after connection was dropped or interrupted.

**Comment by rymurr** [comment]
Thanks a lot for the contribution @kxconor !

**Comment by conorheffron** [comment]
Attaching notes on project setup, use case and debugging.

[Dremio.KDB.Connector.and.APIs.docx](https://github.com/rymurr/dremio-kdb-plugin/files/5113498/Dremio.KDB.Connector.and.APIs.docx)

[Setup Remote Debug Dremio KDB Connector.docx](https://github.com/rymurr/dremio-kdb-plugin/files/5113485/Setup.Remote.Debug.Dremio.KDB.Connector.docx)

**Pull request merged**
